# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: zmmjyokutswxps
  password: YrD8g_xB_CdZ35HjKfzdMWlVB8
  host: ec2-23-21-187-45.compute-1.amazonaws.com


development:
  adapter: postgresql
  database: d364050bm6b5ko
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: d364050bm6b5ko
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d364050bm6b5ko
  pool: 5
  timeout: 5000
